### PR TITLE
Templates (finished?)

### PR DESCRIPTION
**Pull request by chrisjrn**
The sum total of today's work on the templates.

### CODE REVIEW

**Comment by ghost** [comment]
This looks almost ready to go on lcastage, however some of the SVG's are not loading, eg on the /about page, the round image is not loading, and the code points to
`` (file '0' doesn't exist).

**Comment by ghost** [comment]
Also, a bit confused, do I need to merge in my PR #20 or have you merged it in here? (it looks like you copied my PR into #21 and merged it.

**Comment by chrisjrn** [comment]
You can merge just mine, or yours then mine. Take your pick!

I'll need to fix up the cms pages as I've changed a lot of the models, bit
that's OK, we're still in staging!

**Comment by chrisjrn** [comment]
Can you get this on staging asap please?  🙃

**Comment by ghost** [comment]
done

**Pull request merged**
